name: Run My Scraper

on:
  workflow_dispatch:
    inputs:
      website_url:
        description: 'لینکەکە لێرە بنووسە (بۆ نموونە: https://zedflix.tv/)'
        required: true
        default: 'https://zedflix.tv/'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Main Script
        env:
          TARGET_URL: ${{ github.event.inputs.website_url }} # لێرەدا لینکەکە دەدەین بە پایتۆن
        run: python main.py
